### ISSUE TITLE
Vufind debe generar error 404 al no encontrar un registro

### ISSUE THREAD

**Issue by lmatas** [lareferencia/main#103]
Para que los buscadores reconozcan los registros borrados es necesario que vufind genere un error 404 ante un registro no encontrado. 
Es probable que esto se haya solucionado en la versión 2.X, pero es necesario generar un patch para la 1.4. 
http://vufind.2307425.n4.nabble.com/Vufind-doesn-t-return-404-status-for-non-existing-records-urls-td4655419.html

**Comment by miguelius** [comment]
Para el caso de registros que cambiaron de identificación o URL, se puede usar HTTP 301, que es movido permanentemente. Se supone que google lo entiende:
https://support.google.com/webmasters/answer/93633?hl=es

**Comment by albertocabezas** [comment]
Gracias miguelius. Buen punto.

**Comment by lmatas** [comment]
He encontrado donde puede realizarse este cambio para intentar acelerar los cambios en el índice Google. 

Se trata del archivo VuFind/src/VuFind/Bootstrapper.php

Allí se decide precisamente atender a la exception  \VuFind\Exception\RecordMissing con un 404, he realizado el cambio a 301

´´´php

$callback = function ($e) {
            $exception = $e->getParam('exception');
            if (is_object($exception)) {
                if ($exception instanceof \VuFind\Exception\RecordMissing) {
                    // TODO: it might be better to solve this problem by using a
                    // custom RouteNotFoundStrategy.
                    $response = $e->getResponse();
                    if (!$response) {
                        $response = new HttpResponse();
                        $e->setResponse($response);
                    }
                    $response->setStatusCode(301);
                }
            }
        };


´´´

**Comment by lmatas** [comment]
Ahora arroja código 301

![captura de pantalla 2015-06-11 a las 19 43 01](https://cloud.githubusercontent.com/assets/1045370/8120120/30585c02-1072-11e5-8699-8b0e23088176.png)

**Comment by lmatas** [comment]
Aquí más información para considerar - El código 410 Gone y el metatag NOINDEX

**Comment by lmatas** [comment]
Se utiliza ahrra el código 410 y el metatag noindex para páginas erroneas

https://github.com/lareferencia/vufind/commit/3af12df5d91d16de298c2044ad69ba4df7156ef9
