### ISSUE TITLE
Traducción metadata para indexación xoai

### ISSUE THREAD

**Issue by lmatas** [lareferencia/main#107]
Aquí hay un ejemplo de como debe ser indexado el campo item.compile del schema solr para ser utilizado por xoai-provider LAReferencia (legacy XOAI Dspace)

http://codebeautify.org/xmlviewer/b4055f

En el xslt de traducción del indexer XOAI debe transformarse OAIDC a este esquema

**Comment by lmatas** [comment]
Esto es parte del transformador necesario, los tags correspondientes al formato dspace xml deben ser escapeados

<metadata xmlns="http://www.lyncode.com/xoai" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.lyncode.com/xoai http://www.lyncode.com/xsd/xoai.xsd">
                    <element name="dc">
                    
                  	 <element name="title"><xsl:for-each select="//dc:title"><field name="value"><xsl:value-of select="." /></field></xsl:for-each></element>
					 <element name="creator"><xsl:for-each select="//dc:creator"><field name="value"><xsl:value-of select="." /></field></xsl:for-each></element>
					 <element name="subject"><xsl:for-each select="//dc:subject"><field name="value"><xsl:value-of select="." /></field></xsl:for-each></element>
					 <element name="description"><xsl:for-each select="//dc:description"><field name="value"><xsl:value-of select="." /></field></xsl:for-each></element>
					 <element name="publisher"><xsl:for-each select="//dc:publisher"><field name="value"><xsl:value-of select="." /></field></xsl:for-each></element>
					 <element name="contributor"><xsl:for-each select="//dc:contributor"><field name="value"><xsl:value-of select="." /></field></xsl:for-each></element>
					 <element name="date"><xsl:for-each select="//dc:date"><field name="value"><xsl:value-of select="." /></field></xsl:for-each></element>
					 <element name="type"><xsl:for-each select="//dc:type"><field name="value"><xsl:value-of select="." /></field></xsl:for-each></element>
					 <element name="format"><xsl:for-each select="//dc:format"><field name="value"><xsl:value-of select="." /></field></xsl:for-each></element>
					 <element name="identifier"><xsl:for-each select="//dc:identifier"><field name="value"><xsl:value-of select="." /></field></xsl:for-each></element>
					 <element name="source"><xsl:for-each select="//dc:source"><field name="value"><xsl:value-of select="." /></field></xsl:for-each></element>
					 <element name="language"><xsl:for-each select="//dc:language"><field name="value"><xsl:value-of select="." /></field></xsl:for-each></element>
					 <element name="relation"><xsl:for-each select="//dc:relation"><field name="value"><xsl:value-of select="." /></field></xsl:for-each></element>
					 <element name="coverage"><xsl:for-each select="//dc:coverage"><field name="value"><xsl:value-of select="." /></field></xsl:for-each></element>
					 <element name="rights"><xsl:for-each select="//dc:rights"><field name="value"><xsl:value-of select="." /></field></xsl:for-each></element>

               	
                    </element> 
                    
                    <element name="bundles" />
                    
			        <element name="others">
			            <field name="handle"><xsl:value-of select="$vufind_id"/></field>
			            <field name="identifier"><xsl:value-of select="$header_id"/></field>
			            <field name="lastModifyDate">2015-04-15 15:45:39.174</field>
			        </element> 
			        
			        <element name="repository">
			            <field name="mail">mail@mail.com</field>
			            <field name="name"><xsl:value-of select="$networkName"/> - <xsl:value-of select="$institutionName"/></field>
			        </element> 
                    
                </metadata>

**Comment by lmatas** [comment]
&lt;metadata xmlns="http://www.lyncode.com/xoai" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.lyncode.com/xoai http://www.lyncode.com/xsd/xoai.xsd"&gt;
                     &lt;element name="dc"&gt;
                    
                  	 &lt;element name="title"&gt;<xsl:for-each select="//dc:title">&lt;field name="value"&gt;<xsl:value-of select="." />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;
					 &lt;element name="creator"&gt;<xsl:for-each select="//dc:creator">&lt;field name="value"&gt;<xsl:value-of select="." />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;
					 &lt;element name="subject"&gt;<xsl:for-each select="//dc:subject">&lt;field name="value"&gt;<xsl:value-of select="." />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;
					 &lt;element name="description"&gt;<xsl:for-each select="//dc:description">&lt;field name="value"&gt;<xsl:value-of select="." />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;
					 &lt;element name="publisher"&gt;<xsl:for-each select="//dc:publisher">&lt;field name="value"&gt;<xsl:value-of select="." />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;
					 &lt;element name="contributor"&gt;<xsl:for-each select="//dc:contributor">&lt;field name="value"&gt;<xsl:value-of select="." />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;
					 &lt;element name="date"&gt;<xsl:for-each select="//dc:date">&lt;field name="value"&gt;<xsl:value-of select="." />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;
					 &lt;element name="type"&gt;<xsl:for-each select="//dc:type">&lt;field name="value"&gt;<xsl:value-of select="." />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;
					 &lt;element name="format"&gt;<xsl:for-each select="//dc:format">&lt;field name="value"&gt;<xsl:value-of select="." />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;
					 &lt;element name="identifier"&gt;<xsl:for-each select="//dc:identifier">&lt;field name="value"&gt;<xsl:value-of select="." />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;
					 &lt;element name="source"&gt;<xsl:for-each select="//dc:source">&lt;field name="value"&gt;<xsl:value-of select="." />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;
					 &lt;element name="language"&gt;<xsl:for-each select="//dc:language">&lt;field name="value"&gt;<xsl:value-of select="." />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;
					 &lt;element name="relation"&gt;<xsl:for-each select="//dc:relation">&lt;field name="value"&gt;<xsl:value-of select="." />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;
					 &lt;element name="coverage"&gt;<xsl:for-each select="//dc:coverage">&lt;field name="value"&gt;<xsl:value-of select="." />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;
					 &lt;element name="rights"&gt;<xsl:for-each select="//dc:rights">&lt;field name="value"&gt;<xsl:value-of select="." />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;

               	
                    &lt;/element&gt;
                    
                    &lt;element name="bundles" /&gt;
                    
			        &lt;element name="others"&gt;
			            &lt;field name="handle"&gt;<xsl:value-of select="$vufind_id"/>&lt;/field&gt;
			            &lt;field name="identifier"&gt;<xsl:value-of select="$header_id"/>&lt;/field&gt;
			            &lt;field name="lastModifyDate"&gt;2015-04-15 15:45:39.174&lt;/field&gt;
			        &lt;/element&gt;
			        
			        &lt;element name="repository"&gt;
			            &lt;field name="mail"&gt;mail@mail.com&lt;/field&gt;
			            &lt;field name="name"&gt;<xsl:value-of select="$networkName"/> - <xsl:value-of select="$institutionName"/>&lt;/field&gt;
			        &lt;/element&gt;
                    
                &lt;/metadata&gt;

**Comment by lmatas** [comment]
Se suma la exclusión del element cuando el campo no está presente

```xsl
   <field name="item.compile">&lt;metadata xmlns="http://www.lyncode.com/xoai" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.lyncode.com/xoai http://www.lyncode.com/xsd/xoai.xsd"&gt;
                  &lt;element name="dc"&gt;
                      <xsl:if test="//dc:title">&lt;element name="title"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:title">&lt;field name="value"&gt;<xsl:value-of select="." />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:creator">&lt;element name="creator"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:creator">&lt;field name="value"&gt;<xsl:value-of select="." />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:subject">&lt;element name="subject"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:subject">&lt;field name="value"&gt;<xsl:value-of select="." />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:description">&lt;element name="description"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:description">&lt;field name="value"&gt;<xsl:value-of select="." />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:publisher">&lt;element name="publisher"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:publisher">&lt;field name="value"&gt;<xsl:value-of select="." />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:contributor">&lt;element name="contributor"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:contributor">&lt;field name="value"&gt;<xsl:value-of select="." />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:date">&lt;element name="date"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:date">&lt;field name="value"&gt;<xsl:value-of select="." />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:type">&lt;element name="type"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:type">&lt;field name="value"&gt;<xsl:value-of select="." />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:format">&lt;element name="format"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:format">&lt;field name="value"&gt;<xsl:value-of select="." />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:identifier">&lt;element name="identifier"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:identifier">&lt;field name="value"&gt;<xsl:value-of select="." />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:source">&lt;element name="source"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:source">&lt;field name="value"&gt;<xsl:value-of select="." />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:language">&lt;element name="language"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:language">&lt;field name="value"&gt;<xsl:value-of select="." />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:relation">&lt;element name="relation"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:relation">&lt;field name="value"&gt;<xsl:value-of select="." />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:coverage">&lt;element name="coverage"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:coverage">&lt;field name="value"&gt;<xsl:value-of select="." />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:rights">&lt;element name="rights"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:rights">&lt;field name="value"&gt;<xsl:value-of select="." />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                   &lt;/element&gt;

                    &lt;element name="bundles" /&gt;

                    &lt;element name="others"&gt;
                        &lt;field name="handle"&gt;<xsl:value-of select="$header_id"/>&lt;/field&gt;
                        &lt;field name="identifier"&gt;<xsl:value-of select="$header_id"/>&lt;/field&gt;
                        &lt;field name="lastModifyDate"&gt;2015-04-15 15:45:39.174&lt;/field&gt;
                    &lt;/element&gt;

                    &lt;element name="repository"&gt;
                        &lt;field name="mail"&gt;mail@mail.com&lt;/field&gt;
                        &lt;field name="name"&gt;<xsl:value-of select="$networkName"/> - <xsl:value-of select="$institutionName"/>&lt;/field&gt;
                    &lt;/element&gt;

                &lt;/metadata&gt;</field>

```

**Comment by lmatas** [comment]
Se detectaron problemas con la codificación de entidades dentro del contenido, en particular el caso del caracter & que debe ser traducido a &amp; - Internamente se maneja así dentro de LRHarvester, pero en el caso particular de la exportación a XOAI debe "escapearse" doblemente, ya que el texto contenido en item.compile es de por si xml "escapeado".  
Para implementar ese doble escaping fue necesario implementar XSLT2.0 que cuenta con la función replace. Eso soluciona el problema, cuando XOAI realiza su XSLT interno &amp;amp; es transformado a &amp; lo que se corresponde con el comportamiento del paquete original. 

Resta testear que ocurre si hay caracteres como < , > dentro del texto

Caso de test &amp;

http://repositorio.cti.gov.br:8080/oai/request?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:localhost:10691/164

XSLT Resultante
```xsl

<xsl:stylesheet version="2.0"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:fo="http://www.w3.org/1999/XSL/Format"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:fn="http://www.w3.org/2005/xpath-functions"
	xmlns:xdt="http://www.w3.org/2005/xpath-datatypes"
    xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"    
    exclude-result-prefixes="oai_dc dc">
    
    <xsl:output method="xml" indent="yes" encoding="utf-8"/>

	<xsl:param name="networkAcronym" />
	<xsl:param name="networkName" />
	<xsl:param name="institutionName" />
	<xsl:param name="metadata" />
	
	<xsl:param name="vufind_id" />
	<xsl:param name="header_id" />
	<xsl:param name="record_id" />
	
	<xsl:strip-space elements="*"/>
	 
    <xsl:template match="oai_dc:dc">
    
            <doc>
            
                <!-- ID es parámetro -->
                <field name="item.id"><xsl:value-of select="$record_id"/></field>
               
                <!-- ID es parámetro -->
                <field name="item.handle"><xsl:value-of select="$header_id"/></field>   
                
                <field name="item.lastmodified">2015-04-15T18:45:39.174Z</field>    
                
                <field name="item.submitter">submitter</field>    
                
                <field name="item.deleted">false</field>
                <field name="item.public">true</field>    
                
                <field name="item.collections"><xsl:value-of select="$networkAcronym"/></field>
                
                <field name="item.communities">com_<xsl:value-of select="$networkAcronym"/></field>
                
                <xsl:for-each select="//dc:*">
                <field name="metadata.dc.{substring(name(.),4)}"><xsl:value-of select="." /></field>	   
                </xsl:for-each>
             
                
                 <field name="item.compile">&lt;metadata xmlns="http://www.lyncode.com/xoai" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.lyncode.com/xoai http://www.lyncode.com/xsd/xoai.xsd"&gt;
                  &lt;element name="dc"&gt;
                      <xsl:if test="//dc:title">&lt;element name="title"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:title">&lt;field name="value"&gt;<xsl:value-of select="replace(.,'&amp;','&amp;amp;')" />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:creator">&lt;element name="creator"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:creator">&lt;field name="value"&gt;<xsl:value-of select="replace(.,'&amp;','&amp;amp;')" />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:subject">&lt;element name="subject"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:subject">&lt;field name="value"&gt;<xsl:value-of select="replace(.,'&amp;','&amp;amp;')" />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:description">&lt;element name="description"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:description">&lt;field name="value"&gt;<xsl:value-of select="replace(.,'&amp;','&amp;amp;')" />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:publisher">&lt;element name="publisher"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:publisher">&lt;field name="value"&gt;<xsl:value-of select="replace(.,'&amp;','&amp;amp;')" />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:contributor">&lt;element name="contributor"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:contributor">&lt;field name="value"&gt;<xsl:value-of select="replace(.,'&amp;','&amp;amp;')" />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:date">&lt;element name="date"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:date">&lt;field name="value"&gt;<xsl:value-of select="replace(.,'&amp;','&amp;amp;')" />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:type">&lt;element name="type"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:type">&lt;field name="value"&gt;<xsl:value-of select="replace(.,'&amp;','&amp;amp;')" />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:format">&lt;element name="format"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:format">&lt;field name="value"&gt;<xsl:value-of select="replace(.,'&amp;','&amp;amp;')" />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:identifier">&lt;element name="identifier"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:identifier">&lt;field name="value"&gt;<xsl:value-of select="replace(.,'&amp;','&amp;amp;')" />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:source">&lt;element name="source"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:source">&lt;field name="value"&gt;<xsl:value-of select="replace(.,'&amp;','&amp;amp;')" />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:language">&lt;element name="language"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:language">&lt;field name="value"&gt;<xsl:value-of select="replace(.,'&amp;','&amp;amp;')" />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:relation">&lt;element name="relation"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:relation">&lt;field name="value"&gt;<xsl:value-of select="replace(.,'&amp;','&amp;amp;')" />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:coverage">&lt;element name="coverage"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:coverage">&lt;field name="value"&gt;<xsl:value-of select="replace(.,'&amp;','&amp;amp;')" />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:rights">&lt;element name="rights"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:rights">&lt;field name="value"&gt;<xsl:value-of select="replace(.,'&amp;','&amp;amp;')" />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                   &lt;/element&gt;

                    &lt;element name="bundles" /&gt;

                    &lt;element name="others"&gt;
                        &lt;field name="handle"&gt;<xsl:value-of select="$header_id"/>&lt;/field&gt;
                        &lt;field name="identifier"&gt;<xsl:value-of select="$header_id"/>&lt;/field&gt;
                        &lt;field name="lastModifyDate"&gt;2015-04-15 15:45:39.174&lt;/field&gt;
                    &lt;/element&gt;

                    &lt;element name="repository"&gt;
                        &lt;field name="mail"&gt;mail@mail.com&lt;/field&gt;
                        &lt;field name="name"&gt;<xsl:value-of select="$networkName"/> - <xsl:value-of select="$institutionName"/>&lt;/field&gt;
                    &lt;/element&gt;

                &lt;/metadata&gt;</field>
                </doc>
    </xsl:template>
    
</xsl:stylesheet>

```

**Comment by lmatas** [comment]
Queda pendiente test final y casos < >

**Comment by lareferencia** [comment]
Agregados casos de < y > dentro de la transformación de metadata para el campo item.compile

´´´xsl

<xsl:stylesheet version="2.0"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:fo="http://www.w3.org/1999/XSL/Format"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:fn="http://www.w3.org/2005/xpath-functions"
	xmlns:xdt="http://www.w3.org/2005/xpath-datatypes"
    xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"    
    exclude-result-prefixes="oai_dc dc">
    
    <xsl:output method="xml" indent="yes" encoding="utf-8"/>

	<xsl:param name="networkAcronym" />
	<xsl:param name="networkName" />
	<xsl:param name="institutionName" />
	<xsl:param name="metadata" />
	
	<xsl:param name="vufind_id" />
	<xsl:param name="header_id" />
	<xsl:param name="record_id" />
	
	<xsl:strip-space elements="*"/>
	 
    <xsl:template match="oai_dc:dc">
    
            <doc>
            
                
                <field name="item.id"><xsl:value-of select="$record_id"/></field>
               
                
                <field name="item.handle"><xsl:value-of select="$header_id"/></field>   
                
                <field name="item.lastmodified">2015-04-15T18:45:39.174Z</field>    
                
                <field name="item.submitter">submitter</field>    
                
                <field name="item.deleted">false</field>
                <field name="item.public">true</field>    
                
                <field name="item.collections"><xsl:value-of select="$networkAcronym"/></field>
                
                <field name="item.communities">com_<xsl:value-of select="$networkAcronym"/></field>
                
                <xsl:for-each select="//dc:*">
                <field name="metadata.dc.{substring(name(.),4)}"><xsl:value-of select="." /></field>	   
                </xsl:for-each>
             
                
                 <field name="item.compile">&lt;metadata xmlns="http://www.lyncode.com/xoai" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.lyncode.com/xoai http://www.lyncode.com/xsd/xoai.xsd"&gt;
                  &lt;element name="dc"&gt;
                      <xsl:if test="//dc:title">&lt;element name="title"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:title">&lt;field name="value"&gt;<xsl:value-of select="replace(replace(replace(.,'&amp;','&amp;amp;'),'&lt;','&amp;lt;'),'&amp;gt;','&gt;')" />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:creator">&lt;element name="creator"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:creator">&lt;field name="value"&gt;<xsl:value-of select="replace(replace(replace(.,'&amp;','&amp;amp;'),'&lt;','&amp;lt;'),'&amp;gt;','&gt;')" />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:subject">&lt;element name="subject"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:subject">&lt;field name="value"&gt;<xsl:value-of select="replace(replace(replace(.,'&amp;','&amp;amp;'),'&lt;','&amp;lt;'),'&amp;gt;','&gt;')" />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:description">&lt;element name="description"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:description">&lt;field name="value"&gt;<xsl:value-of select="replace(replace(replace(.,'&amp;','&amp;amp;'),'&lt;','&amp;lt;'),'&amp;gt;','&gt;')" />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:publisher">&lt;element name="publisher"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:publisher">&lt;field name="value"&gt;<xsl:value-of select="replace(replace(replace(.,'&amp;','&amp;amp;'),'&lt;','&amp;lt;'),'&amp;gt;','&gt;')" />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:contributor">&lt;element name="contributor"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:contributor">&lt;field name="value"&gt;<xsl:value-of select="replace(replace(replace(.,'&amp;','&amp;amp;'),'&lt;','&amp;lt;'),'&amp;gt;','&gt;')" />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:date">&lt;element name="date"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:date">&lt;field name="value"&gt;<xsl:value-of select="replace(replace(replace(.,'&amp;','&amp;amp;'),'&lt;','&amp;lt;'),'&amp;gt;','&gt;')" />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:type">&lt;element name="type"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:type">&lt;field name="value"&gt;<xsl:value-of select="replace(replace(replace(.,'&amp;','&amp;amp;'),'&lt;','&amp;lt;'),'&amp;gt;','&gt;')" />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:format">&lt;element name="format"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:format">&lt;field name="value"&gt;<xsl:value-of select="replace(replace(replace(.,'&amp;','&amp;amp;'),'&lt;','&amp;lt;'),'&amp;gt;','&gt;')" />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:identifier">&lt;element name="identifier"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:identifier">&lt;field name="value"&gt;<xsl:value-of select="replace(replace(replace(.,'&amp;','&amp;amp;'),'&lt;','&amp;lt;'),'&amp;gt;','&gt;')" />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:source">&lt;element name="source"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:source">&lt;field name="value"&gt;<xsl:value-of select="replace(replace(replace(.,'&amp;','&amp;amp;'),'&lt;','&amp;lt;'),'&amp;gt;','&gt;')" />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:language">&lt;element name="language"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:language">&lt;field name="value"&gt;<xsl:value-of select="replace(replace(replace(.,'&amp;','&amp;amp;'),'&lt;','&amp;lt;'),'&amp;gt;','&gt;')" />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:relation">&lt;element name="relation"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:relation">&lt;field name="value"&gt;<xsl:value-of select="replace(replace(replace(.,'&amp;','&amp;amp;'),'&lt;','&amp;lt;'),'&amp;gt;','&gt;')" />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:coverage">&lt;element name="coverage"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:coverage">&lt;field name="value"&gt;<xsl:value-of select="replace(replace(replace(.,'&amp;','&amp;amp;'),'&lt;','&amp;lt;'),'&amp;gt;','&gt;')" />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                      <xsl:if test="//dc:rights">&lt;element name="rights"&gt;&lt;element name="none"&gt;<xsl:for-each select="//dc:rights">&lt;field name="value"&gt;<xsl:value-of select="replace(replace(replace(.,'&amp;','&amp;amp;'),'&lt;','&amp;lt;'),'&amp;gt;','&gt;')" />&lt;/field&gt;</xsl:for-each>&lt;/element&gt;&lt;/element&gt;</xsl:if>
                   &lt;/element&gt;

                    &lt;element name="bundles" /&gt;

                    &lt;element name="others"&gt;
                        &lt;field name="handle"&gt;<xsl:value-of select="$header_id"/>&lt;/field&gt;
                        &lt;field name="identifier"&gt;<xsl:value-of select="$header_id"/>&lt;/field&gt;
                        &lt;field name="lastModifyDate"&gt;2015-04-15 15:45:39.174&lt;/field&gt;
                    &lt;/element&gt;

                    &lt;element name="repository"&gt;
                        &lt;field name="mail"&gt;mail@mail.com&lt;/field&gt;
                        &lt;field name="name"&gt;<xsl:value-of select="$networkName"/> - <xsl:value-of select="$institutionName"/>&lt;/field&gt;
                    &lt;/element&gt;

                &lt;/metadata&gt;</field>
                </doc>
    </xsl:template>
    
</xsl:stylesheet>

´´´

**Comment by lareferencia** [comment]
Reporte de caso de error, colección periódicos BR

Identifier:
oai:agregador.ibict.br.PERIODICOS:oai:periodicos.ibict.br.Acta_Scientiarum_Agronomy:oai:periodicos.uem.br:article/5374

error reportado por parser xml
SystemId Unknown; Line #3; Column #2029; The content of elements must consist of well-formed character data or markup.

**Comment by lareferencia** [comment]
Aparentemente el problema se produce con caracteres no imprimibles, falta verificar en la fuente original.

<element name="none">
        <field name="value">Elaboração de um guia com estratégias para Resoluções de Problemas de Mecânica visando a aprendizagem significativa dos alunos do 1º ano de ensino Médio</field>
 </element>

**Comment by lareferencia** [comment]
Resuelto! Era error en la expresión de replace, la correcta es:

```xls
replace(replace(replace(.,'&amp;','&amp;amp;'),'&lt;','&amp;lt;'),'&gt;','&amp;gt;')
```

También agregada la fechahora de modificación en tiempo de indexación:

```xsl
<xsl:value-of  select="format-dateTime(current-dateTime(), '[Y0001]-[M01]-[D01]T[H01]:[m01]:[s01]Z')"/>
```   

Resta definir si los replace anidados son la mejor forma de resolver el problema o existe algo más elegante/eficiente en xslt 2.0
