### ISSUE TITLE
Acrónimo Repositorio

### ISSUE THREAD

**Issue by teleuko** [lareferencia/main#110]
Incrementar la cantidad de caracteres.

**Comment by lareferencia** [comment]
Dado que es utilizado en la llamada de servicios es importante mantenerlo acotado y controlado, mayúsculas y no mas de N caracteres sin espacios. Con N < 10 opino
Actualmente no se valida lo que se ingresa, pero sería importante hacerlo

**Comment by Pao-MINCYT** [comment]
N < 10 estaría bien, creemos que sería suficiente.

**Comment by miguelius** [comment]
N = 8 alcanza.

Porque N=1 satisface el N<1 pero es poco práctico...

**Comment by Pao-MINCYT** [comment]
Me parece que con 10 (máximos) nos quedamos más tranquilos.

**Comment by lmatas** [comment]
Implementado UI Admin Harvester v3.0
