### ISSUE TITLE
Mejoras en la interfaz de diagnóstico para cada Repositorio (en las implementaciones nacionales)

### ISSUE THREAD

**Issue by Pao-MINCYT** [lareferencia/main#112]
Sería bueno contar con esto, para poder darle su propia URL de seguimiento a cada repositorio de los nodos nacionales.

**Comment by lareferencia** [comment]
Eso ya está garantizado, la genera el botón diagnóstico (para cada repositorio) dentro del admin de backend.
La interfaz de diagnóstico debe mejorar, debo dar una vuelta al tema de No_Detectados y hacerlo más transparente y claro para el usuario.

**Comment by Pao-MINCYT** [comment]
Entonces no dije nada! Gracias!

**Comment by gruporepositorio** [comment]
Entre las mejoras para los diagnósticos de los Repositorios, sería bueno que al tener el listado de Registros, sea rechazados por alguna razón como válidos, se presente un listado con mayor número de elementos que 15, de ser posible personalizable el valor de paginación.

**Comment by gruporepositorio** [comment]
En el mismo contexto con los diagnósticos, se podría plantear un campo de búsqueda que permita filtrar (así se busque en todo el XML), sería útil en el caso de identificar registros.

**Comment by lmatas** [comment]
Implementado UI Admin Harvester v3.0
