### ISSUE TITLE
Evaluar la restricción de longitud de RT en el objeto NetworkSnapshot

### ISSUE THREAD

**Issue by lareferencia** [lareferencia/main#118]
Actualmente se agregó un truncamiento debido a problemas generados por redes gran número de repositorios. El provider de LR genera RT cuya longitud crece en función de la cantidad de repositorios. Esto queda subsanado con la implementación de XOAI como provider de LRHarvester. Sin embargo es necesario evaluarlo porque podría ocasionar problemas cosechando otros providers.

Solución temporal de restricción en:
https://github.com/lareferencia/main/commit/4ebfee2e31e6e85a82e0f9e46ef69f000ecab74a

**Comment by lmatas** [comment]
Esto fue solucionado con el cambio del OAI Provider por XOAI
