### ISSUE TITLE
Status das redes na tela de administração

### ISSUE THREAD

**Issue by wtonribeiro** [lareferencia/main#123]
Seria bastante importante termos uma coluna (de preferência a primeira) na tela principal de administração com o status da rede (VALID, HARVESTING , HARVESTING_ERROR, ...). Isso ajudaria muito o administrador na obtenção de um panorama da rede como um todo, sem precisar entrar em cada nó.

**Comment by lmatas** [comment]
Esto ha sido resuelto en la interfaz de administración backend 3.0
