### ISSUE TITLE
Sistema retorna error quando se busca por "http://x"

### ISSUE THREAD

**Issue by wtonribeiro** [lareferencia/main#124]
Quando se realiza busca pelo termo "http://x" o sistema retorna um error.
![error_busca](https://cloud.githubusercontent.com/assets/7083604/8655006/ab56c08c-2964-11e5-9789-63d30c16c7ec.png)
![error_busca2](https://cloud.githubusercontent.com/assets/7083604/8655048/f1fed3e4-2964-11e5-9c91-aadf44b3589e.png)

**Comment by lmatas** [comment]
Haciendo algunas pruebas he encontrado que la falla se replica con el string minimal:
x://x

**Comment by lmatas** [comment]
Este bug es de vufind, lo copio en el repo vufind
