### ISSUE TITLE
Percentual de ocorrência de cada termo em um dado campo

### ISSUE THREAD

**Issue by wtonribeiro** [lareferencia/main#126]
No novo validador, seria interessante que houve a descrição do percentual de cada termo no relatório. Exemplo é o que ocorre no validador RCAAP (segue imagem)
![validador_rcaap](https://cloud.githubusercontent.com/assets/7083604/9880369/acf0f358-5ba1-11e5-8bdc-548197aaf044.png)
.

**Comment by lmatas** [comment]
Esto ha sido resuelto en la interfaz de diagnóstico Backend 3.0
